### ISSUE TITLE
Some countries are missing on server

### ISSUE THREAD

**Issue by devemux86** [mapsforge/mapsforge-mapcreator#2]
Include more countries in map creation process on server.

**Comment by peter17** [comment]
I am interested in adding more maps polygons to this repository. How are the .poly files created? Are the coordinates extracted from OpenStreetMap? Is there a script and/or tutorial somewere?
Best regards.

**Comment by applantation** [comment]
No, no and no.
Some of the original polygons came from geofabrik.de, but we got all those.
Essentially, we need a tight outline that is contained in the parent area.
The format is pretty simple, the are text files with more or less just the
polygon points.
Am 28.04.2015 5:22 nachm. schrieb "Peter Potrowl" <notifications@github.com

**Comment by devemux86** [comment]
Note that we have already included the polygons for many countries, they just aren't in the map generation process yet (we should definitely add them with the capital as start position).

BTW Nepal would be a good start.

**Comment by devemux86** [comment]
With 352509203637e3ef839efe9512872e810eb89f2e I added Nepal.
The polygon is from Geofabrik and the start position is the capital coordinates.

**Comment by ludwigb** [comment]
I will update the server and restart, thanks.

**Comment by peter17** [comment]
I answer my  own comment:
There are a lot of `.poly` files that can be downloaded there: https://osm.wno-edv-service.de/boundaries/

The problem is that those files are quite big (e.g. 36 MB for the 96 French departements = sub-regions). However, I was able to use the first line of those files to identify the administrative polygon ID on OSM. Once you have this ID, you can generate more `.poly` files using this tool: http://polygons.openstreetmap.fr/index.py

This tool allows downlading polygons "as is" (about same size as with the 1st URL) OR "simplified". This time, the 96 `.poly` corresponding to the French departements total 1.2 MB which I find reasonnable.

I will push those to my repo in a few moments. I still have to find the coordinates of the "capitals".

I think the two web services I linked can be used to generate all the `.poly` files for (almost?) all the countries in the world.

**Comment by devemux86** [comment]
What `poly` would we need, simplified?

**Comment by peter17** [comment]
"Simplification" is just a way to reduce the file size, because imho, the `.poly` files for OSM contain too much information.

For instance, on this image http://polygons.openstreetmap.fr/get_image.py?id=1450201&params=0.002000-0.001000-0.001000 the (original) green polygon is 382 KB where the (simplified) blue one is only 13 KB...

Without this "simplification", the repo with polygons for all countries will take hundreds of MB, with files that will take longer times to process...

**Comment by devemux86** [comment]
With the above series of commits I added all remaining countries that we have their polygons (using their capitals as start positions).

I'm closing this, for any region request please open a new issue.
